package Challenges;

import java.util.Scanner;
/*


You are given a one dimensional array that may contain both positive and negative integers, find the sum of contiguous subarray of numbers which has the largest sum. For example, if the given array is {-2, -5, 6, -2, -3, 1, 5, -6}, then the maximum subarray sum is 7.

Input Format
The first line consists of number of test cases T. Each test case consists of two lines.
The first line of each testcase contains a single integer N denoting the number of elements for the array A.
The second line of each testcase contains N space separated integers denoting the elements of the array.

Constraints
1 <= N <= 100000

1 <= t <= 20

 -100000000 <= A[i] <= 100000000

Output Format
Output a single integer denoting the maximum subarray sum for each testcase in a new line.

Sample Input
2
4
1 2 3 4
3
-10 5 10
Sample Output

10
15

Explanation
For the first testcase, maximum subarray sum is generated by the entire array - 1+2+3+4 = 10
For the second testcase , maximum subarray sum is generated by the subarray {5,10} - 5+10 = 15








 */
public class Maximumsubarraysum {

	public static void main(String[] args) {
		Scanner scan =new Scanner(System.in);
		System.out.println("enter total no of values to find in subarray");
		int number=scan.nextInt();
		for(int i=0;i<number;i++)
		{
			System.out.println("enter total no of values in first array");
			int n=scan.nextInt();
			int [] array=new int[n];
			
			for(int j=0;j<array.length;j++)
			{
				System.out.println("enter "+j+"st value in array");
				array[j]=scan.nextInt();
			}
			
			int[] array1=subarray(array);
			
		int max=	Arraymax(array1);
		System.out.println(max);
		}
		
		

	}

	
	public static int[] subarray(int[] array)
	{
		int[] array1 =new int[array.length];
		for(int i=0;i<array.length;i++)
		{
			int sum=0;
			for(int j=i;j<array.length;j++)
			{
				sum=sum+array[j];
				
				
			}
		
		array1[i]=sum;
		}
		return array1;
	}
	
	
	
	
	public static int Arraymax(int[] arr)
	{
		int max=Integer.MIN_VALUE;
		
		for(int i=0;i<arr.length;i++)
		{
			if(arr[i]>max)
			{
				max=arr[i];
			}
		}
		return max;
		
	}
	
}
